
Config 				  = {}
Config.UseESX 		  = true
Config.CooldownPolice = 1000 -- Will work with ESX only
Config.cooldown		  = 3000

-- Add/remove weapon hashes here to be added for holster checks.
Config.Weapons = {
	"WEAPON_PISTOL",
	"WEAPON_COMBATPISTOL",
	"WEAPON_APPISTOL",
	"WEAPON_PISTOL50",
	"WEAPON_SNSPISTOL",
	"WEAPON_HEAVYPISTOL",
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_MARKSMANPISTOL",
	"WEAPON_MACHINEPISTOL",
	"WEAPON_PISTOL_MK2",
	"WEAPON_SNSPISTOL_MK2",
	"WEAPON_FLAREGUN",
	"WEAPON_STUNGUN",
	"WEAPON_REVOLVER",
	"weapon_revolver_mk2",
	"weapon_doubleaction",
	"weapon_raypistol",
	"weapon_ceramicpistol",
	"weapon_navyrevolver",
	"WEAPON_FLARE",
	"WEAPON_KNIFE",
	"WEAPON_KNUCKLE",
	"WEAPON_NIGHTSTICK",
	"WEAPON_HAMMER",
	"WEAPON_BAT",
	"WEAPON_GOLFCLUB",
	"WEAPON_CROWBAR",
	"WEAPON_BOTTLE",
	"WEAPON_DAGGER",
	"WEAPON_HATCHET",
	"WEAPON_MACHETE",
	"weapon_grenade",
	"WEAPON_BZGAS",
	"weapon_molotov",
	"weapon_stickybomb",
	"WEAPON_PROXMINE",
	"weapon_pipebomb",
	"weapon_flare",
	"WEAPON_SMOKEGRENADE",
	"WEAPON_MACHINEPISTOL",
	"weapon_microsmg",
	"weapon_minismg",
	"weapon_flashlight",
	"weapon_wrench",
	"weapon_battleaxe",
	"weapon_poolcue",
	"weapon_stone_hatchet",
	"weapon_autoshotgun",
	"weapon_dbshotgun",
}
